### ISSUE TITLE
Is it the 3'UTR of NOTCH or NOTCH2?

### ISSUE THREAD

**Issue by paolahernandez** [paolahernandez/miRNAs_prostate#1]
Hey @said3427 
En el fasta Alignment5.fasta me aparece el nombre de la secuencia 3'UTR como NOTCH nada más. ¿Fue error de dedo? El gen al que se predijo pega es NOTCH2. Plase, advice :1st_place_medal:

**Comment by said3427** [comment]
Los transcritos de NOTCH2 son: ENST00000602566.1 y ENST00000256646.2; buena observación. Ya subí los transcritos que sí son NOTCH2 @paolahernandez

**Comment by paolahernandez** [comment]
Pero nada más deben de ser los 3'UTR, ¿O por qué se ven tan largotas esas secuencias? @said3427
