### ISSUE TITLE
CCND1 - ¿Hay un overlap entre el 3'UTR y el ORF?

### ISSUE THREAD

**Issue by paolahernandez** [paolahernandez/miRNAs_prostate#3]
¿O por qué hay letras en minúscula y en mayuscula?
Please, advise @said3427

**Comment by said3427** [comment]
Las secuencias estaban alineadas originalmente con otros UTRs de varias especies. 

UTR consensus sequence is uppercase at "highly conserved" positions and lowercase at "conserved" positions.
